### ISSUE TITLE
Link, spelling, formatting and description errors

### ISSUE THREAD

**Issue by Menghua1** [MiguelElGallo/simple-fastapi-snow-azd#5]
1.
**Describe the issue:**
Link error 404.
![image](https://github.com/MiguelElGallo/simple-fastapi-snow-azd/assets/111940661/4e5919d0-77b1-44c9-b39d-639ca0237ad4)
**Suggestion:**
Update the link to `https://github.com/MiguelElGallo/simple-fastapi-snow-azd`.

2.
**Describe the issue:**
Document format error.
![image](https://github.com/MiguelElGallo/simple-fastapi-snow-azd/assets/111940661/73be7259-cfcf-49aa-b7ef-ce7603c8571d)
**Suggestion:**
Remove redundant "========" and "```".

3.
**Describe the issue:**
Formatting, capitalization, word spelling, description errors.
![image](https://github.com/MiguelElGallo/simple-fastapi-snow-azd/assets/111940661/90bd0f99-9739-4150-881a-577e44474b85)
**Suggestion:**
1. Update `THIS STEP IS MANDATORY` to `this step is mandatory`.
2. Update `xxxxxx.region.hyperscaler` to `youraccountidentifier`.
3. Update `yourpassworr` to `yourpassword`.

@MiguelElGallo and @hemarina for notification.

**Comment by MiguelElGallo** [comment]
Hello @v-xuto,
All observations have been corrected. Thanks! 
Miguel
