### ISSUE TITLE
Failed to execute "azd pipeline config"

### ISSUE THREAD

**Issue by Menghua1** [MiguelElGallo/simple-fastapi-snow-azd#6]
**Describe the issue:**
Executing the command `azd pipeline config` failed, the following error was encountered:
![image](https://github.com/MiguelElGallo/simple-fastapi-snow-azd/assets/111940661/948b99d0-703e-4087-a823-d1d421c723e4)

**Repro Steps:**
1. Run `azd init -t MiguelElGallo/simple-fastapi-snow-azd`.
2. Run `azd pipeline config`.

**Expected behavior:**
The command `azd pipeline config` can be run successfully.

@MiguelElGallo and @hemarina for notification.

**Comment by MiguelElGallo** [comment]
Hello @Menghua1 and @v-xuto,
I did not had the corresponding folder, now it has been added and tested. 
Thanks!
PS.: Will be good if you add this to your documentation , meaning that support for pipelines is a MUST
