### ISSUE TITLE
Failed to execute "Run and Debug" 

### ISSUE THREAD

**Issue by Menghua1** [MiguelElGallo/simple-fastapi-snow-azd#7]
**Describe the issue:**
According to [Readme.md](https://github.com/MiguelElGallo/simple-fastapi-snow-azd?tab=readme-ov-file#testing-locally), when executing the third step of `Testing locally` and clicking the `Run and Debug` button, the following error was encountered:
![image](https://github.com/MiguelElGallo/simple-fastapi-snow-azd/assets/111940661/aa32a475-c7e1-44b3-b555-0b87eb110b90)
![image](https://github.com/MiguelElGallo/simple-fastapi-snow-azd/assets/111940661/c9967ff5-195a-4788-aece-138e270c7c53)
At this time, a reminder from the "Azure Functions" extension appears in the lower right corner. After clicking `Yes`, click the `Run and Debug` button again, and encountered another problem, as shown below:
![image](https://github.com/MiguelElGallo/simple-fastapi-snow-azd/assets/111940661/95b5b75f-3ac9-461f-8601-17858c1623f7)
After press F1, search for and select `Azurite: Start.`, it can run successfully.

**Repro Steps:**
1. Run `azd init -t MiguelElGallo/simple-fastapi-snow-azd`.
2. Create a [Python virtual environment](https://docs.python.org/3/tutorial/venv.html#creating-virtual-environments) and activate it.
3. Run `python3 -m pip install -r requirements.txt`.
4. Click the "Run and Debug" button.

**Expected behavior:**
After clicking the `Run and Debug` button, it can be run successfully.

@MiguelElGallo and @hemarina for notification.

**Comment by MiguelElGallo** [comment]
Hello @v-xuto,
Thanks for this I've added step 3 related to Azurite. 
Please note that, those steps where copied from here: https://github.com/Azure-Samples/openai-plugin-fastapi
(MS provided template) 
And there installing and starting azurite is also missing.
Cheers,
Miguel

**Comment by Menghua1** [comment]
@MiguelElGallo after clicking the `Run and Debug` button, the error shown below will still be encountered: 
According to the error message, `${config:azureFunctions.pythonVenv}` is used in the `.vscode/task.json` file, but this template does not define the variable `azureFunctions.pythonVenv`.
![image](https://github.com/MiguelElGallo/simple-fastapi-snow-azd/assets/111940661/13f7cad7-c09f-4142-84cc-a0dddfcd2162)
After clicking `Yes` in the reminder of the "Azure Functions" extension in the lower right corner, the `.vscode/settings.json` file is created with the following content. Click the `Run and Debug` button again and it will work successfully.
![image](https://github.com/MiguelElGallo/simple-fastapi-snow-azd/assets/111940661/6533a437-1740-4fd2-9355-a8e44145b422)
Here are my two suggestions:
1. Add the `.vscode/settings.json` file and the configuration of the `azureFunctions.pythonVenv` variable.
2. Add a **Note** In Readme.md to prompt the user to click `Yes` when seeing a pop-up box about initializing the project from the "Azure Functions" extension.

**Comment by MiguelElGallo** [comment]
Hello @Menghua1 ,
Thanks for the suggestions , but I was not able to reproduce the error.
As you can see  [here:] (https://youtu.be/EpJlLx0-k4c)

Also my settings.json

```
{
    "azureFunctions.deploySubpath": ".",
    "azureFunctions.scmDoBuildDuringDeployment": true,
    "azureFunctions.pythonVenv": ".venv",
    "azureFunctions.projectLanguage": "Python",
    "azureFunctions.projectRuntime": "~4",
    "debug.internalConsoleOptions": "neverOpen",
    "azureFunctions.projectLanguageModel": 2
}
```

As you can see already contains the azureFunctions.pythonVenv variable.

Can you please confirm?
Thanks!

**Comment by MiguelElGallo** [comment]
@Menghua1 Sorry, my bad. 
I had in .gitignore:
`.vscode/settings.json`
Now I removed and the file is in the Repo.
Thanks again and sorry :)
Cheers!

**Comment by Menghua1** [comment]
@MiguelElGallo According to the [link](https://docs.python.org/3/tutorial/venv.html#creating-virtual-environments) to create a Python virtual environment in [Readme.md](https://github.com/MiguelElGallo/simple-fastapi-snow-azd/tree/main?tab=readme-ov-file#testing-locally), the default name of the created virtual environment is `tutorial-env`.
But the `azureFunctions.pythonVenv` value specified is `.venv` in this Repo's `.vscode/settings.json` file.
![image](https://github.com/MiguelElGallo/simple-fastapi-snow-azd/assets/111940661/1bad6b2a-7950-49fc-a3e6-9bc07411567e)
Here are my two suggestions:
1. Modify the value of `azureFunctions.pythonVenv` to `tutorial-env` in the `.vscode/settings.json` file
2. Or add **Note** to Readme.md. If the name of the created python virtual environment is not `.venv`, please change the package name of the virtual environment to `.venv`.

**Comment by MiguelElGallo** [comment]
@Menghua1 updated Readme.md with a note.
Cheers!
